"use client";
import type { CollectionConfig } from "../components/CollectionManager";

const CATEGORY_SUGGESTIONS = [
  "Custom Software",
  "E-commerce",
  "Logistics",
  "Healthcare",
  "Internal Tools",
  "SaaS",
  "Infrastructure",
  "DevOps",
];

const seo = [
  { type: "section" as const, label: "Search & sharing", help: "Optional. Sensible defaults are generated from the content when left empty." },
  { type: "text" as const, name: "seo_title", label: "Meta title", max: 70, help: "Up to ~60 characters shows fully in Google." },
  { type: "textarea" as const, name: "seo_description", label: "Meta description", max: 200, rows: 2 },
  { type: "image" as const, name: "og_image", label: "Social share image", folder: "og", aspect: 1200 / 630, crop: true, help: "1200×630. Defaults to the site’s share image." },
];

export const projectsConfig: CollectionConfig = {
  table: "projects",
  title: "Projects",
  singular: "project",
  description:
    "Concise portfolio entries that show the breadth of our work. Star a project to feature it on the homepage (3–4 is ideal). Drafts are never visible on the site.",
  columns:
    "id, slug, title, category, project_type, summary, description, client_id, client_name, cover_image, gallery, tech_stack, services, url, confidential, featured, published, sort_order, start_date, end_date, seo_title, seo_description, og_image",
  titleField: "title",
  subtitle: (r) => [r.category, r.summary].filter(Boolean).join(" — "),
  publish: { field: "published", on: true, off: false },
  featured: true,
  viewPath: (r) => `/projects/${r.slug}`,
  slugFrom: "title",
  defaults: { published: false, featured: false, confidential: false, gallery: [], tech_stack: [], services: [], category: "" },
  fields: [
    { type: "text", name: "title", label: "Title", required: true, max: 150 },
    { type: "slug", name: "slug", label: "URL slug", required: true, max: 80, help: "Used in the page address: /projects/your-slug. Generated from the title." },
    { type: "suggest", name: "category", label: "Category", required: true, max: 100, suggestions: CATEGORY_SUGGESTIONS, help: "Pick a suggestion or type a new category." },
    { type: "text", name: "project_type", label: "Project type", max: 80, placeholder: "e.g. Production system, Internal tool, MVP" },
    { type: "textarea", name: "summary", label: "Short description", required: true, max: 500, rows: 2, help: "One or two sentences shown on cards." },
    { type: "textarea", name: "description", label: "Full description", max: 5000, rows: 8, help: "Shown on the project page. Plain paragraphs; separate with a blank line." },
    { type: "tags", name: "services", label: "What we built", help: "e.g. Backend & APIs, AWS infrastructure, CI/CD. Press Enter after each." },
    { type: "tags", name: "tech_stack", label: "Technology stack", help: "Only technologies genuinely used in this project." },
    { type: "section", label: "Client" },
    { type: "relation", name: "client_id", label: "Client", table: "clients", help: "Only shown publicly if the client allows public display and the project isn’t confidential." },
    { type: "toggle", name: "confidential", label: "Confidential", help: "Confidential — never show the client name, logo or project link" },
    { type: "url", name: "url", label: "Public project URL", help: "Optional link to the live product (hidden when confidential)." },
    { type: "section", label: "Media" },
    { type: "image", name: "cover_image", label: "Cover image", folder: "projects", aspect: 16 / 10, crop: true },
    { type: "gallery", name: "gallery", label: "Screenshots", folder: "projects" },
    { type: "section", label: "Timeline" },
    { type: "date", name: "start_date", label: "Start date" },
    { type: "date", name: "end_date", label: "End date", help: "Leave empty for ongoing work." },
    { type: "section", label: "Visibility" },
    { type: "toggle", name: "published", label: "Published", help: "Published — visible on the site" },
    { type: "toggle", name: "featured", label: "Featured", help: "Featured — show on the homepage" },
    ...seo,
  ],
};

export const caseStudiesConfig: CollectionConfig = {
  table: "case_studies",
  title: "Case studies",
  singular: "case study",
  description:
    "Deeper technical stories. The first featured, published case study appears on the homepage. Keep it factual: never invent metrics, and never include IPs, hostnames, ports or other internal details.",
  columns:
    "id, slug, title, project_id, client_id, anonymized, headline, summary, challenge, solution, outcome, responsibilities, technologies, metrics, architecture, cover_image, gallery, featured, published, sort_order, seo_title, seo_description, og_image",
  titleField: "title",
  subtitle: (r) => String(r.headline ?? ""),
  publish: { field: "published", on: true, off: false },
  featured: true,
  viewPath: (r) => `/case-studies/${r.slug}`,
  slugFrom: "title",
  defaults: {
    published: false,
    featured: false,
    anonymized: true,
    responsibilities: [],
    technologies: [],
    metrics: [],
    architecture: [],
    gallery: [],
  },
  fields: [
    { type: "text", name: "title", label: "Title", required: true, max: 150, help: "When anonymized this is the public name, e.g. “Production Commerce Platform”." },
    { type: "slug", name: "slug", label: "URL slug", required: true, max: 80 },
    { type: "text", name: "headline", label: "Headline", max: 160, placeholder: "e.g. Engineered for 5,000+ concurrent users" },
    { type: "textarea", name: "summary", label: "Summary", max: 600, rows: 3 },
    { type: "relation", name: "project_id", label: "Related project", table: "projects" },
    { type: "relation", name: "client_id", label: "Client", table: "clients" },
    { type: "toggle", name: "anonymized", label: "Anonymized", help: "Anonymized — never show the client name on the site" },
    { type: "section", label: "Engineering story", help: "Short and factual. Empty sections are hidden." },
    { type: "tags", name: "responsibilities", label: "What we own", help: "e.g. Backend & APIs, AWS infrastructure, Monitoring & backups." },
    { type: "textarea", name: "challenge", label: "Challenge", max: 3000, rows: 4 },
    { type: "textarea", name: "solution", label: "Solution / architecture", max: 5000, rows: 6 },
    { type: "textarea", name: "outcome", label: "Outcome", max: 3000, rows: 3 },
    { type: "tags", name: "technologies", label: "Technologies & infrastructure" },
    { type: "metrics", name: "metrics", label: "Verified metrics", help: "Only real, verifiable numbers." },
    { type: "section", label: "Architecture diagram" },
    { type: "architecture", name: "architecture", label: "Components" },
    { type: "section", label: "Media" },
    { type: "image", name: "cover_image", label: "Cover image", folder: "case-studies", aspect: 16 / 10, crop: true },
    { type: "gallery", name: "gallery", label: "Screenshots", folder: "case-studies" },
    { type: "section", label: "Visibility" },
    { type: "toggle", name: "published", label: "Published", help: "Published — visible on the site" },
    { type: "toggle", name: "featured", label: "Featured", help: "Featured — show on the homepage" },
    ...seo,
  ],
};

export const clientsConfig: CollectionConfig = {
  table: "clients",
  title: "Clients",
  singular: "client",
  description:
    "Companies we’ve worked with. A client only appears on the site when “Public display permission” is on. Only add logos you have permission to use.",
  columns: "id, name, logo, website, industry, description, is_public, featured, sort_order",
  titleField: "name",
  subtitle: (r) => [r.industry, r.website].filter(Boolean).join(" · "),
  publish: { field: "is_public", on: true, off: false, onLabel: "Public", offLabel: "Private" },
  featured: true,
  defaults: { is_public: false, featured: false, website: "", industry: "", description: "" },
  fields: [
    { type: "text", name: "name", label: "Company name", required: true, max: 150 },
    { type: "image", name: "logo", label: "Logo", folder: "logos", help: "PNG or WebP with a transparent background works best." },
    { type: "url", name: "website", label: "Website" },
    { type: "text", name: "industry", label: "Industry", max: 80 },
    { type: "textarea", name: "description", label: "Relationship", max: 300, rows: 2, help: "Internal note, e.g. what we built for them." },
    { type: "section", label: "Visibility" },
    { type: "toggle", name: "is_public", label: "Public display permission", help: "We have permission to show this client publicly" },
    { type: "toggle", name: "featured", label: "Featured", help: "Featured — show on the homepage" },
  ],
};

export const testimonialsConfig: CollectionConfig = {
  table: "testimonials",
  title: "Testimonials",
  singular: "testimonial",
  description:
    "Real client quotes only. Submissions from the public form arrive as Pending; approve them to publish. Up to three appear on the homepage, featured first.",
  columns:
    "id, name, role, company, company_logo, profile_url, quote, rating, status, project_id, featured, sort_order, created_at",
  titleField: "name",
  subtitle: (r) => [r.role, r.company].filter(Boolean).join(", ") + ` — “${String(r.quote ?? "").slice(0, 80)}…”`,
  publish: { field: "status", on: "approved", off: "pending", onLabel: "Approved", offLabel: "Pending" },
  featured: true,
  defaults: { status: "approved", rating: 5, featured: false, company: "", profile_url: "" },
  fields: [
    { type: "textarea", name: "quote", label: "Quote", required: true, max: 1000, rows: 4 },
    { type: "text", name: "name", label: "Client name", required: true, max: 100 },
    { type: "text", name: "role", label: "Role / title", required: true, max: 150 },
    { type: "text", name: "company", label: "Company", max: 150 },
    { type: "image", name: "company_logo", label: "Company logo", folder: "logos" },
    { type: "url", name: "profile_url", label: "LinkedIn / profile URL" },
    { type: "relation", name: "project_id", label: "Related project", table: "projects" },
    { type: "number", name: "rating", label: "Rating (1–5)" },
    { type: "section", label: "Visibility" },
    {
      type: "select",
      name: "status",
      label: "Status",
      options: [
        { value: "approved", label: "Approved — published" },
        { value: "pending", label: "Pending review" },
        { value: "rejected", label: "Rejected" },
      ],
    },
    { type: "toggle", name: "featured", label: "Featured", help: "Featured — prefer on the homepage" },
  ],
};

export const teamConfig: CollectionConfig = {
  table: "team_members",
  title: "Team",
  singular: "team member",
  description: "The people who work on client projects. Published members appear in the homepage team section, in this order.",
  columns: "id, name, initials, role, focus, linkedin, photo, published, sort_order",
  titleField: "name",
  subtitle: (r) => [r.role, r.focus].filter(Boolean).join(" · "),
  publish: { field: "published", on: true, off: false },
  defaults: { published: false, linkedin: "", focus: "", role: "", initials: "" },
  fields: [
    { type: "text", name: "name", label: "Name", required: true, max: 100 },
    { type: "text", name: "initials", label: "Initials", max: 3, help: "Shown when there’s no photo." },
    { type: "text", name: "role", label: "Role", max: 80, placeholder: "e.g. Co-founder" },
    { type: "text", name: "focus", label: "Technical responsibility", max: 160, placeholder: "e.g. Backend & AWS infrastructure" },
    { type: "url", name: "linkedin", label: "LinkedIn URL" },
    { type: "image", name: "photo", label: "Photo", folder: "team", aspect: 1, crop: true, help: "Square, real photo. No stock images." },
    { type: "toggle", name: "published", label: "Published", help: "Published — visible on the site" },
  ],
};

export const servicesConfig: CollectionConfig = {
  table: "services",
  title: "Capabilities",
  singular: "capability",
  description: "The capability pillars on the homepage (ideally three). List only tools the team genuinely uses.",
  columns: "id, title, description, icon, features, tools, published, sort_order",
  titleField: "title",
  subtitle: (r) => String(r.description ?? ""),
  publish: { field: "published", on: true, off: false },
  defaults: { published: false, icon: "Code2", features: [], tools: [] },
  fields: [
    { type: "text", name: "title", label: "Title", required: true, max: 100 },
    { type: "textarea", name: "description", label: "Description", max: 500, rows: 2 },
    {
      type: "select",
      name: "icon",
      label: "Icon",
      options: ["Code2", "Cloud", "GitBranch", "Layers", "Server", "Workflow"].map((v) => ({ value: v, label: v })),
    },
    { type: "tags", name: "features", label: "What’s included" },
    { type: "tags", name: "tools", label: "Tools" },
    { type: "toggle", name: "published", label: "Published", help: "Published — visible on the site" },
  ],
};

export const faqsConfig: CollectionConfig = {
  table: "faqs",
  title: "FAQs",
  singular: "question",
  description: "Questions that remove buying friction. Keep the homepage to about five.",
  columns: "id, topic, question, short_answer, answer, link_label, link_href, show_on_home, published, sort_order",
  titleField: "question",
  subtitle: (r) => String(r.short_answer ?? ""),
  publish: { field: "published", on: true, off: false },
  defaults: { published: false, show_on_home: true, topic: "", short_answer: "", link_label: "", link_href: "" },
  fields: [
    { type: "text", name: "question", label: "Question", required: true, max: 200 },
    { type: "text", name: "topic", label: "Topic label", max: 40, placeholder: "e.g. After launch" },
    { type: "text", name: "short_answer", label: "Short answer", max: 200, help: "One bold sentence." },
    { type: "textarea", name: "answer", label: "Answer", required: true, max: 1500, rows: 4 },
    { type: "text", name: "link_label", label: "Link label", max: 40, placeholder: "e.g. Start a project" },
    { type: "text", name: "link_href", label: "Link target", max: 200, placeholder: "/#contact or /agency-partners" },
    { type: "toggle", name: "show_on_home", label: "Show on homepage", help: "Show on the homepage" },
    { type: "toggle", name: "published", label: "Published", help: "Published — visible on the site" },
  ],
};
